import React, { Suspense } from "react"
import { RefineKbarProvider } from "@refinedev/kbar"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import "@refinedev/antd/dist/reset.css"
import "../styles/globals.css"
import SessionProviderWrapper from "./providers/auth-provider/AuthProvider"
import ClientWrapper from "./clientRoot"

export const metadata = {
  title: "OWNERSHIP",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico"
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="test" suppressHydrationWarning>
        <SessionProviderWrapper>
          <Suspense>
            <RefineKbarProvider>
              <AntdRegistry>
                <ClientWrapper>{children}</ClientWrapper>
              </AntdRegistry>
            </RefineKbarProvider>
          </Suspense>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
